Update ngxdelete

diff --git a/bin/ngxdelete b/bin/ngxdelete
--- a/bin/ngxdelete
+++ b/bin/ngxdelete
@@ -35,20 +35,28 @@ if [ -z "$1" ]; then
     fi
   done
 else
-  defdomain="$1"
-  set -- "$(basename $defdomain)"
-  item_remove=("${nginx_available}/$defdomain")
-  if [ -L "${nginx_enabled}/$defdomain" ]; then
-    while [[ ! $forceremove =~ ^[yYnN]$ ]]; do
-      read -s -n1 -p "Do you want remove the symlink for $defdomain too ? (y/n)" forceremove
-      echo
-      case $forceremove in
-        [Yy]* ) item_remove+=("${nginx_enabled}/$defdomain");;
-        [Nn]* ) exit 1;;
-        * ) echo "Invalid input" >&2;;
-      esac
-    done
-  fi
+  item_remove=()
+  for optsite in "$@"; do
+    set -- "$(basename $optsite)"
+    if [ -f "${nginx_available}/$optsite" ]; then
+      item_remove+=("${nginx_available}/$optsite")
+      if [ -L "${nginx_enabled}/$optsite" ]; then
+        while [[ ! $forceremove =~ ^[yYnN]$ ]]; do
+          read -s -n1 -p "Do you want remove the symlink for $optsite too ? (y/n)" forceremove
+          echo
+          case $forceremove in
+            [Yy]* ) item_remove+=("${nginx_enabled}/$optsite");;
+            [Nn]* ) continue;;
+            * ) echo "Invalid input" >&2;;
+          esac
+        done
+        unset forceremove
+      fi
+    else
+      echo "$optsite does not exist" >&2
+      continue
+    fi
+  done
 fi
 printf "Removing --> %s\n" "${item_remove[@]}"
 rm -f "${item_remove[@]}"
