Commit changes

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -4,9 +4,18 @@ if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
 else
+  scriptdir=$(dirname "$(readlink -f "$0")")
   printf "Removing nginx site wrapper script..."
   rm -f /usr/local/bin/ngxensite /usr/local/bin/ngxdissite /usr/local/bin/ngxcreate /root/.ngx_donotremove /etc/bash_completion.d/nginxsite_complete
   mv /etc/nginx/.nginx.conf.ngx_backup /etc/nginx/nginx.conf
-  sleep 1
+  read -s -n1 -p "Do you want to remove this (script) directory ? (y/n)" wantremove
+  echo
+  while [[ ! $wantremove =~ ^[yYnN]$ ]]; do
+    case "$wantremove" in
+      [Yy]* ) /bin/rm -r "$scriptdir"; echo "$scriptdir deleted" '!';;
+      [Nn]* ) exit 0;;
+      * ) echo "Invalid choice" >&2;;
+    esac
+  done
   printf ' Done !\n'
 fi
